# Generated by Django 5.1.1 on 2025-03-30 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('email_id', models.EmailField(max_length=150, unique=True)),
                ('college_name', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('resume_pdf', models.FileField(upload_to='resumes/')),
            ],
        ),
    ]
