# Generated by Django 5.1.7 on 2025-03-30 17:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerform',
            old_name='date_of_birth',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='registerform',
            old_name='contact_number',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='registerform',
            name='email_id',
        ),
        migrations.RemoveField(
            model_name='registerform',
            name='resume_pdf',
        ),
        migrations.RemoveField(
            model_name='registerform',
            name='roll_number',
        ),
        migrations.AddField(
            model_name='registerform',
            name='application_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='registerform',
            name='cgpa',
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registerform',
            name='current_degree',
            field=models.CharField(choices=[('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech'), ('PhD', 'PhD'), ('Other', 'Other')], default='B.Tech', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registerform',
            name='email',
            field=models.EmailField(default='temporary@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registerform',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Prefer not to say', 'Prefer not to say')], default='Male', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registerform',
            name='lor',
            field=models.FileField(blank=True, null=True, upload_to='uploads/lors/'),
        ),
        migrations.AddField(
            model_name='registerform',
            name='resume',
            field=models.FileField(default=2, upload_to='uploads/resumes/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registerform',
            name='special_preference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registerform',
            name='college_name',
            field=models.CharField(max_length=100),
        ),
    ]
